seed_pow: ../shared-f08/universe2d.f08 ../shared-f08/histogram.f08 ecmc_serial.f08
	gfortran -o seed_pow -O3 -flto -Wall -Wextra ../shared-f08/universe2d.f08 ../shared-f08/histogram.f08 ecmc_serial.f08
